use_frameworks!

platform :ios, '10.0'

target 'FlipperEventStoreVieweriOS_Example' do
  pod 'FlipperEventStoreVieweriOS', :path => '../'

  target 'FlipperEventStoreVieweriOS_Tests' do
    inherit! :search_paths

    
  end
end
